namespace:
  name: prod 
 
service:
  port: 7111
  type: ClusterIP

image:
  repository: veerabhadraiahhv/techtrends 
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    memory: 256Mi
    cpu: 500m
